# Generated by Django 3.1.7 on 2021-03-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_userpics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='userPics',
            field=models.ImageField(default='user.jpg', null=True, upload_to='user/profilepics/%d/%m/'),
        ),
    ]
