# Generated by Django 3.1.7 on 2021-07-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sponsoredpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsoredpost',
            name='user',
        ),
    ]
