# Generated by Django 3.1.7 on 2021-04-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210317_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='earningLimit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Free', 'Free')], default='Free', max_length=30),
        ),
    ]
