# Generated by Django 3.1.7 on 2021-07-27 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_sponsoredpost_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenSponsoredPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sponsored_postSeen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sponsoredpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
