# Generated by Django 3.1.7 on 2021-08-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_seensponsoredpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneypost',
            name='image_link',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
