# Generated by Django 3.1.7 on 2021-04-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210407_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='who_is_getting_payed',
            field=models.BooleanField(blank=True, choices=[('Iffilate', 'Iffilate'), ('User', 'User')], null=True),
        ),
    ]
