# Generated by Django 3.1.7 on 2021-04-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payhistory_who_is_getting_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhistory',
            name='who_is_getting_payed',
            field=models.CharField(blank=True, choices=[('Iffilate', 'Iffilate'), ('User', 'User')], max_length=10, null=True),
        ),
    ]
