# Generated by Django 3.1.7 on 2021-08-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_moneypost_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneypost',
            name='image_link',
            field=models.CharField(default='none', max_length=1000, null=True),
        ),
    ]
