# Generated by Django 3.1.7 on 2021-04-27 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_moneypost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenMoneyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postSeen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.moneypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
