# Generated by Django 3.1.7 on 2021-05-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userrequestpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestpayment',
            name='account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userrequestpayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userrequestpayment',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userrequestpayment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userrequestpayment',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
