# Generated by Django 3.1.7 on 2021-05-30 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210524_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestpayment',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
