# Generated by Django 3.1.7 on 2021-07-07 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleDrawBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAmountPaid_to_game', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('is_close', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('when', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaffleDrawPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPayed', models.BooleanField(default=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=30)),
                ('is_winner', models.BooleanField(default=False)),
                ('raffle_draw_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raffleDraw.raffledrawbatch')),
            ],
        ),
    ]
