# Generated by Django 3.1.7 on 2021-06-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffleDraw', '0002_auto_20210701_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffledrawplayer',
            name='isPayed',
            field=models.BooleanField(default=False),
        ),
    ]
