# Generated by Django 3.1.7 on 2021-07-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffleDraw', '0003_raffledrawplayer_ispayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raffledrawplayer',
            name='account_number',
        ),
        migrations.AddField(
            model_name='raffledrawplayer',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
