# Generated by Django 3.1.7 on 2021-07-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffleDraw', '0003_remove_raffledrawbatch_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffledrawplayer',
            name='account_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
