# Generated by Django 3.1.7 on 2021-07-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffleDraw', '0004_auto_20210701_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffledrawplayer',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
