# Generated by Django 3.1.7 on 2021-07-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffleDraw', '0006_raffledrawplayer_is_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffledrawbatch',
            name='when',
            field=models.DateTimeField(null=True),
        ),
    ]
