# Generated by Django 3.1.7 on 2021-03-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iffliateLanding_page', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='contentImage',
            field=models.ImageField(null=True, upload_to='iffliateLanding_page/Blog/%m/%d/'),
        ),
    ]
