# Generated by Django 3.1.7 on 2021-03-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iffliateLanding_page', '0003_blog_contentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
